## Janitor
- type: quickPhrase
  id: SpillPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-spill

- type: quickPhrase
  id: CleanadePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cleanade

- type: quickPhrase
  id: CartPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-cart

- type: quickPhrase
  id: LightTubePhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-light-tube

- type: quickPhrase
  id: LightBulbPhrase
  parent: BaseServiceSubjectPhrase
  text: phrase-light-bulb
